spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

mybatis:
  type-aliases-package: com.didim.project1
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

jwt:
  secret-key: ${JWT_SECRET_KEY}
#  access-expired: 300 # 5분
  access-expired: 7200 # 2시간
  refresh-expired: 7200 # 2시간

road-address:
  api-key: ${ROAD_ADDRESS_API_KEY}

#logging:
#  level:
#    hello.board.repository.mybatis: trace